//! FBT Build Studio — clone firmware repos, manage fbt_options_local.py, run builds.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::{Deserialize, Serialize};
use walkdir::WalkDir;

use crate::error::{FlipperError, Result};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FbtConfig {
    pub firmware_origin: String,
    pub firmware_app_set: String,
    pub extra_int_apps: Vec<String>,
    pub extra_ext_apps: Vec<String>,
    pub update_splash: String,
    pub loader_autostart: String,
    pub extra_defines: Vec<String>,
}

impl Default for FbtConfig {
    fn default() -> Self {
        Self {
            firmware_origin: "DeezFW".into(),
            firmware_app_set: "default".into(),
            extra_int_apps: vec![],
            extra_ext_apps: vec![],
            update_splash: "update_default".into(),
            loader_autostart: String::new(),
            extra_defines: vec![],
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct AppManifestEntry {
    pub appid: String,
    pub name: Option<String>,
    pub apptype: Option<String>,
    pub path: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct FbtArtifact {
    pub path: String,
    pub kind: String,
    pub size_bytes: u64,
    pub modified_secs: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct FirmwareBase {
    pub id: String,
    pub name: String,
    pub url: String,
}

fn fbt_script(repo: &Path) -> PathBuf {
    #[cfg(windows)]
    {
        let cmd = repo.join("fbt.cmd");
        if cmd.exists() {
            return cmd;
        }
    }
    repo.join("fbt")
}

fn render_fbt_options_local(config: &FbtConfig) -> String {
    let int_apps = config.extra_int_apps.join(",");
    let ext_apps = config.extra_ext_apps.join(",");
    let defines = config
        .extra_defines
        .iter()
        .map(|d| format!("    \"{d}\","))
        .collect::<String>();
    format!(
        r#"# Auto-generated by Deez Flipper Tools — do not edit fbt_options.py
Import("fbt_options")

env = DefaultEnvironment()

env.Append(
    FIRMWARE_ORIGIN="{origin}",
    FIRMWARE_APP_SET="{app_set}",
    UPDATE_SPLASH="{splash}",
    LOADER_AUTOSTART="{autostart}",
)

# Extra apps passed on CLI when building:
# --extra-int-apps={int_apps}
# --extra-ext-apps={ext_apps}
# --extra-define flags:
{defines}
"#,
        origin = config.firmware_origin,
        app_set = config.firmware_app_set,
        splash = config.update_splash,
        autostart = config.loader_autostart,
        int_apps = int_apps,
        ext_apps = ext_apps,
        defines = if defines.is_empty() {
            "    # (none)".to_string()
        } else {
            defines
        },
    )
}

fn parse_simple_fbt_options(content: &str) -> FbtConfig {
    let mut cfg = FbtConfig::default();
    for line in content.lines() {
        let line = line.trim();
        if let Some(v) = line.strip_prefix("FIRMWARE_ORIGIN=") {
            cfg.firmware_origin = v.trim_matches('"').trim_matches('\'').to_string();
        }
        if let Some(v) = line.strip_prefix("FIRMWARE_APP_SET=") {
            cfg.firmware_app_set = v.trim_matches('"').trim_matches('\'').to_string();
        }
        if let Some(v) = line.strip_prefix("UPDATE_SPLASH=") {
            cfg.update_splash = v.trim_matches('"').trim_matches('\'').to_string();
        }
        if let Some(v) = line.strip_prefix("LOADER_AUTOSTART=") {
            cfg.loader_autostart = v.trim_matches('"').trim_matches('\'').to_string();
        }
    }
    cfg
}

#[tauri::command]
pub fn fbt_firmware_bases() -> Vec<FirmwareBase> {
    vec![
        FirmwareBase {
            id: "official".into(),
            name: "Official Flipper Firmware".into(),
            url: "https://github.com/flipperdevices/flipperzero-firmware".into(),
        },
        FirmwareBase {
            id: "momentum".into(),
            name: "Momentum Firmware".into(),
            url: "https://github.com/Next-Flip/Momentum-Firmware".into(),
        },
        FirmwareBase {
            id: "unleashed".into(),
            name: "Unleashed Firmware".into(),
            url: "https://github.com/DarkFlippers/unleashed-firmware".into(),
        },
    ]
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_clone_repo(url: String, target_dir: String) -> Result<String> {
    tauri::async_runtime::spawn_blocking(move || {
        let target = PathBuf::from(&target_dir);
        if target.exists() {
            return Err(FlipperError::Internal(format!(
                "Target already exists: {}",
                target.display()
            )));
        }
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        let status = Command::new("git")
            .args(["clone", "--recursive", "--jobs", "8", &url, target_dir.as_str()])
            .status()
            .map_err(FlipperError::Io)?;
        if status.success() {
            Ok(target_dir)
        } else {
            Err(FlipperError::Internal("git clone failed".into()))
        }
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_scan_manifests(repo_path: String) -> Result<Vec<AppManifestEntry>> {
    tauri::async_runtime::spawn_blocking(move || {
        let repo = PathBuf::from(&repo_path);
        let mut entries = Vec::new();
        for entry in WalkDir::new(&repo).into_iter().filter_map(|e| e.ok()) {
            if entry.file_name() != "application.fam" {
                continue;
            }
            let path = entry.path();
            let text = fs::read_to_string(path)?;
            for block in text.split("App(") {
                let appid = extract_fam_field(block, "appid");
                if appid.is_empty() {
                    continue;
                }
                entries.push(AppManifestEntry {
                    appid,
                    name: extract_fam_field_opt(block, "name"),
                    apptype: extract_fam_field_opt(block, "apptype"),
                    path: path.to_string_lossy().into_owned(),
                });
            }
        }
        entries.sort_by(|a, b| a.appid.cmp(&b.appid));
        entries.dedup_by(|a, b| a.appid == b.appid);
        Ok(entries)
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

fn extract_fam_field(block: &str, key: &str) -> String {
    extract_fam_field_opt(block, key).unwrap_or_default()
}

fn extract_fam_field_opt(block: &str, key: &str) -> Option<String> {
    let needle = format!("{key}=");
    let start = block.find(&needle)? + needle.len();
    let rest = block[start..].trim_start();
    if rest.starts_with('"') {
        let end = rest[1..].find('"')? + 1;
        return Some(rest[1..end].to_string());
    }
    let end = rest.find(|c: char| c == ',' || c == ')').unwrap_or(rest.len());
    Some(rest[..end].trim().to_string())
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_read_config(repo_path: String) -> Result<FbtConfig> {
    tauri::async_runtime::spawn_blocking(move || {
        let path = PathBuf::from(&repo_path).join("fbt_options_local.py");
        if path.exists() {
            let text = fs::read_to_string(path)?;
            Ok(parse_simple_fbt_options(&text))
        } else {
            Ok(FbtConfig::default())
        }
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_write_config(repo_path: String, config: FbtConfig) -> Result<()> {
    tauri::async_runtime::spawn_blocking(move || {
        let path = PathBuf::from(&repo_path).join("fbt_options_local.py");
        fs::write(path, render_fbt_options_local(&config))?;
        Ok(())
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_list_artifacts(repo_path: String) -> Result<Vec<FbtArtifact>> {
    tauri::async_runtime::spawn_blocking(move || {
        let repo = PathBuf::from(&repo_path);
        let mut artifacts = Vec::new();
        for sub in ["build", "dist"] {
            let dir = repo.join(sub);
            if !dir.exists() {
                continue;
            }
            for entry in WalkDir::new(&dir).into_iter().filter_map(|e| e.ok()) {
                if !entry.file_type().is_file() {
                    continue;
                }
                let path = entry.path();
                let ext = path
                    .extension()
                    .and_then(|e| e.to_str())
                    .unwrap_or("")
                    .to_lowercase();
                let kind = match ext.as_str() {
                    "dfu" => "dfu",
                    "tgz" => "tgz",
                    "fap" => "fap",
                    _ => continue,
                };
                let meta = match entry.metadata() {
                    Ok(m) => m,
                    Err(_) => continue,
                };
                let modified = meta
                    .modified()
                    .ok()
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_secs())
                    .unwrap_or(0);
                artifacts.push(FbtArtifact {
                    path: path.to_string_lossy().into_owned(),
                    kind: kind.to_string(),
                    size_bytes: meta.len(),
                    modified_secs: modified,
                });
            }
        }
        artifacts.sort_by(|a, b| b.modified_secs.cmp(&a.modified_secs));
        Ok(artifacts)
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_run(
    repo_path: String,
    target: String,
    extra_args: Vec<String>,
    config: Option<FbtConfig>,
) -> Result<i32> {
    tauri::async_runtime::spawn_blocking(move || {
        let repo = PathBuf::from(&repo_path);
        if let Some(cfg) = config {
            let path = repo.join("fbt_options_local.py");
            fs::write(path, render_fbt_options_local(&cfg))?;
        }
        let script = fbt_script(&repo);
        if !script.exists() {
            return Err(FlipperError::Internal(
                "fbt script not found in firmware repo".into(),
            ));
        }
        let mut args = vec![target];
        args.extend(extra_args);
        let status = Command::new(&script)
            .args(&args)
            .current_dir(&repo)
            .status()
            .map_err(FlipperError::Io)?;
        Ok(status.code().unwrap_or(-1))
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub fn fbt_profiles_dir() -> Result<String> {
    let dir = dirs::data_local_dir()
        .ok_or_else(|| FlipperError::Internal("no local data dir".into()))?
        .join("Deez Flipper Tools")
        .join("fbt-profiles");
    fs::create_dir_all(&dir)?;
    Ok(dir.to_string_lossy().into_owned())
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_save_profile(name: String, config: FbtConfig) -> Result<()> {
    tauri::async_runtime::spawn_blocking(move || {
        let dir = PathBuf::from(fbt_profiles_dir()?);
        let safe: String = name
            .chars()
            .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect();
        let path = dir.join(format!("{safe}.json"));
        fs::write(path, serde_json::to_string_pretty(&config)?)?;
        Ok(())
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_load_profile(name: String) -> Result<FbtConfig> {
    tauri::async_runtime::spawn_blocking(move || {
        let dir = PathBuf::from(fbt_profiles_dir()?);
        let safe: String = name
            .chars()
            .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect();
        let path = dir.join(format!("{safe}.json"));
        let text = fs::read_to_string(path)?;
        Ok(serde_json::from_str(&text)?)
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fbt_list_profiles() -> Result<Vec<String>> {
    tauri::async_runtime::spawn_blocking(move || {
        let dir = PathBuf::from(fbt_profiles_dir()?);
        let mut names = Vec::new();
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    names.push(stem.to_string());
                }
            }
        }
        names.sort();
        Ok(names)
    })
    .await
    .map_err(|e| FlipperError::Internal(e.to_string()))?
}
